### ISSUE TITLE
Revise flow sensitive typing on conditionals

### ISSUE THREAD

**Issue by randoum** [soutaro/steep#319] opened 2021-03-04 10:49 UTC
Similar to #131 

When a type is defined as optional (i.e `String?`), the validation does not take into account that the current context verified the presence of the value.

## To reproduce

```
# class_a.rb

class ClassA
  attr_accessor :member
end

a = ClassA.new
a.member = 'Test'

unless a.member.nil?
  b = a.member * 3
end
```

```
# class_a.rbs

class ClassA
  attr_accessor member: ::String?
end
```

`$ bundle exec steep check`

```
class_a.rb:9:15: [error] Type `(::String | nil)` does not have method `*`
│ Diagnostic ID: Ruby::NoMethod
│
└   b = a.member * 3
                 ~
```

**Comment by soutaro** [comment] 2021-03-12 08:48
This is expected behavior because `a.member` is a method call and technically it can return different values on each call.

A workaround is assigning it to a local variable.

```rb
unless (member = a.member).nil?
  b = member * 3
end
```

I know it sometimes overkills for this and relaxing the restriction which requires _value_ might make more sense...

**Comment by soutaro** [comment] 2021-03-16 00:40
Closing the issue. Related to #334.

**Closed by soutaro** 2021-03-16 00:40 UTC
